- name: stack setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import vpc setup variables
      include_vars: vars/output_vars

    - name: Import ec2 setup variables
      include_vars: vars/stacksetup

    - name: create a new EC2 key pair
      amazon.aws.ec2_key:
        name: vpro-key
        region: "{{region}}"
      register: vprokey_out

    - name: save private key into file loginkey_vpro.pem
      copy:
         content: "{{vprokey_out.key.private_key}}"
         dest: "./loginkey_vpro.pem"
         mode: 0600
      when: vprokey_out.changed

    - name: create SG for LB
      amazon.aws.ec2_security_group:
         name: SG_ELB
         region: "{{region}}"
         description: allow port 80 form everywhere
         vpc_id: "{{vpcid}}"
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
      register: SGELB_out   
   
    - name: create SG for ec2
      amazon.aws.ec2_security_group:
         name: SG_EC2
         region: "{{region}}"
         description: allow port 22 form everywhere
         vpc_id: "{{vpcid}}"
         purge_rules: no
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{SGLB_out.group_id}}"
            rule_desc: allow all on port 80

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{bastionsg_out}}"
      register: SGEC2_out   
      
    - name: update SG with its own sg id
      amazon.aws.ec2_security_group:
        name: SG_EC2
        region: "{{region}}"
        description: allow port 22 form everywhere
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
         - proto: all
           group_id: "{{SGEC2_out.group_id}}"
            
    